name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up python3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: install dependency
      run: |
        make install

    - name: Lint with pylint
      run: |
        make lint

    - name: Test with pytest
      run: |
        make test
